# coding: utf-8

MAIN_WINDOW_MIN_HEIGHT = 600
MAIN_WINDOW_MIN_WIDTH = 800

MAIN_WINDOW_HEIGHT = 600
MAIN_WINDOW_WIDTH = 800

MAIN_WINDOW_X = 0
MAIN_WINDOW_Y = 0

DATE_TIME_FORMAT = u'%Y-%m-%d %H:%M:%S'
DATE_TIME_FORMAT_EXIF = u'%Y:%m:%d %H:%M:%S'


